-keep class com.borzsoft.smsgateway.** { *; }
-keep class fi.iki.elonen.** { *; }
-keep class com.google.gson.** { *; }
-keep class com.google.zxing.** { *; }
-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod
-dontwarn fi.iki.elonen.**
-dontwarn com.google.errorprone.**
